"""empty message

Revision ID: 69280f501f7d
Revises: 
Create Date: 2022-09-03 17:48:10.570839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69280f501f7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('text_color', sa.Text(), nullable=False),
    sa.Column('background_color', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
